# Generated by Django 4.2.16 on 2024-09-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('address', models.TextField()),
                ('lab_image', models.ImageField(blank=True, null=True, upload_to='laboratory/images/')),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('phone_number', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=128)),
                ('lab_commission', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('file', models.FileField(blank=True, null=True, upload_to='laboratory/files/')),
                ('is_recommended', models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=0)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'laboratories',
            },
        ),
    ]
