# Generated by Django 4.2.16 on 2024-09-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H2H_admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laboratory',
            old_name='is_recommended',
            new_name='emergency_services',
        ),
        migrations.RemoveField(
            model_name='laboratory',
            name='file',
        ),
        migrations.RemoveField(
            model_name='laboratory',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='laboratory',
            name='accreditations_certifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='alternate_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Alternate Number'),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='city',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laboratory',
            name='contact_number',
            field=models.CharField(default=None, max_length=15, verbose_name='Contact Number (or Phone Number)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laboratory',
            name='home_sample_collection',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='insurance_accepted',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='location_map',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='operating_hours',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laboratory',
            name='payment_methods',
            field=models.CharField(choices=[('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('Cash', 'Cash')], default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laboratory',
            name='postal_code',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laboratory',
            name='promote',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0, verbose_name='Promote'),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='report_delivery_options',
            field=models.CharField(choices=[('Online', 'Online'), ('Email', 'Email'), ('Physical Copy', 'Physical Copy')], default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laboratory',
            name='specializations',
            field=models.CharField(blank=True, choices=[('pediatric_diagnostics', 'Pediatric Diagnostics'), ('cardiac_diagnostics', 'Cardiac Diagnostics'), ('general_practice', 'General Practice')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='state_province',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laboratory',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='description',
            field=models.TextField(verbose_name='About the Center (or Description)'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='email',
            field=models.EmailField(max_length=150, verbose_name='Email (or Email Address)'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='lab_image',
            field=models.ImageField(blank=True, null=True, upload_to='laboratory/images/', verbose_name='Photos of Lab Center (or Lab Image)'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='lab_name',
            field=models.CharField(max_length=150, verbose_name='Center Name (or Lab Name)'),
        ),
    ]
