# Generated by Django 4.2.16 on 2024-11-19 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_hospitalimage_table'),
        ('H2H_admin', '0002_alter_ward_table_bed'),
    ]

    operations = [
        migrations.CreateModel(
            name='BedStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Assigned'), (0, 'Empty')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bed_statuses', to='H2H_admin.bed')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bed_statuses', to='accounts.hospital')),
            ],
            options={
                'db_table': 'bed_status',
            },
        ),
    ]
