# Generated by Django 4.2.16 on 2024-11-19 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_hospitalimage_table'),
        ('H2H_admin', '0003_bedstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
                ('service_icon', models.ImageField(blank=True, null=True, upload_to='hospital/service_icons/')),
                ('starting_from', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='accounts.hospital')),
            ],
        ),
    ]
