# Generated by Django 4.2.16 on 2024-11-19 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('H2H_admin', '0004_hospitalservice'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hospitalservice',
            table='hospital_service',
        ),
    ]
