# Generated by Django 4.2.16 on 2024-10-07 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('H2H_admin', '0004_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_services', to='H2H_admin.laboratory')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_services', to='H2H_admin.service')),
            ],
            options={
                'db_table': 'lab_services',
            },
        ),
    ]
