# Generated by Django 4.2.16 on 2024-10-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H2H_admin', '0005_labservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='labservice',
            name='is_emergency_service',
            field=models.BooleanField(default=False),
        ),
    ]
