# Generated by Django 4.2.16 on 2024-10-07 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('H2H_admin', '0006_labservice_is_emergency_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, max_length=250, null=True)),
                ('banner', models.ImageField(upload_to='lab_banners/', verbose_name='Banner Image')),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='H2H_admin.laboratory')),
            ],
            options={
                'db_table': 'lab_banners',
            },
        ),
    ]
