# Generated by Django 4.2.16 on 2024-11-25 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_doctordetails_join_date'),
        ('H2H_admin', '0015_labtag_service_labservice_labbanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Staff Name')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=150, unique=True, verbose_name='Email Address')),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='laboratory/staff_profiles/', verbose_name='Profile Image')),
                ('qualification', models.CharField(max_length=255, verbose_name='Qualification')),
                ('experience', models.PositiveIntegerField(verbose_name='Years of Experience')),
                ('staff_type', models.CharField(choices=[('technician', 'Technician'), ('pathologist', 'Pathologist'), ('radiologist', 'Radiologist'), ('sample_collector', 'Sample Collector')], max_length=20, verbose_name='Staff Type')),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_staff', to='accounts.laboratory', verbose_name='Laboratory')),
            ],
            options={
                'verbose_name': 'Lab Staff',
                'verbose_name_plural': 'Lab Staff',
                'db_table': 'lab_staff',
            },
        ),
        migrations.CreateModel(
            name='LabPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_specialization', models.CharField(blank=True, choices=[('pediatric_diagnostics', 'Pediatric Diagnostics'), ('cardiac_diagnostics', 'Cardiac Diagnostics'), ('general_practice', 'General Practice')], max_length=100, null=True, verbose_name='Lab Specialization')),
                ('package_name', models.CharField(max_length=150, verbose_name='Package Name')),
                ('test_preparation', models.TextField(blank=True, null=True, verbose_name='Test Preparation Instructions')),
                ('package_img', models.ImageField(blank=True, null=True, upload_to='laboratory/packages/', verbose_name='Package Image')),
                ('expected_delivery', models.CharField(max_length=50, verbose_name='Expected Delivery')),
                ('lab_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Lab Price')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sale Price')),
                ('promote', models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0, verbose_name='Promote')),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=0, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_packages', to='accounts.laboratory', verbose_name='Lab Center')),
                ('lab_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_packages', to='H2H_admin.labservice', verbose_name='Lab Service')),
                ('lab_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_packages', to='H2H_admin.labtag', verbose_name='Lab Tag')),
            ],
            options={
                'db_table': 'lab_packages',
            },
        ),
    ]
