# Generated by Django 4.2.16 on 2024-11-27 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('H2H_admin', '0016_labstaff_labpackage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppModule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('module_name', models.CharField(max_length=150)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'App_module',
            },
        ),
        migrations.CreateModel(
            name='OfferBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, max_length=250, null=True)),
                ('banners', models.CharField(max_length=200)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_banners', to='H2H_admin.appmodule')),
            ],
            options={
                'db_table': 'module_offer_banners',
            },
        ),
        migrations.CreateModel(
            name='ModuleBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.CharField(max_length=250)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_banners', to='H2H_admin.appmodule')),
            ],
            options={
                'db_table': 'module_banners',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, max_length=250, null=True)),
                ('banners', models.CharField(max_length=200)),
                ('position', models.CharField(default='top', max_length=50)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='H2H_admin.appmodule')),
            ],
            options={
                'db_table': 'banners',
            },
        ),
    ]
