# Generated by Django 4.2.16 on 2024-11-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H2H_admin', '0017_appmodule_offerbanner_modulebanner_banner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OfferBanner',
            new_name='ModuleOfferBanner',
        ),
        migrations.AlterField(
            model_name='banner',
            name='position',
            field=models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom')], default='top', max_length=50),
        ),
        migrations.AlterModelTable(
            name='appmodule',
            table='app_module',
        ),
        migrations.DeleteModel(
            name='ModuleBanner',
        ),
    ]
