# Generated by Django 4.2.16 on 2024-11-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H2H_admin', '0018_rename_offerbanner_moduleofferbanner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='banners',
        ),
        migrations.RemoveField(
            model_name='moduleofferbanner',
            name='banners',
        ),
        migrations.AddField(
            model_name='banner',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
        migrations.AddField(
            model_name='moduleofferbanner',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
    ]
