# Generated by Django 4.2.16 on 2024-11-28 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_customer_created_at_and_more'),
        ('H2H_admin', '0019_remove_banner_banners_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertTalk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expert_talks', to='accounts.doctordetails')),
            ],
            options={
                'verbose_name': 'Expert Talk',
                'verbose_name_plural': 'Expert Talks',
                'db_table': 'expert_talks',
            },
        ),
    ]
