# Generated by Django 4.2.16 on 2024-11-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H2H_admin', '0021_bedbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedbooking',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='in_progress', max_length=15),
        ),
    ]
