# Generated by Django 4.2.16 on 2024-12-03 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_customer_created_at_and_more'),
        ('H2H_admin', '0022_alter_bedbooking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experttalk',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expert_talks', to='accounts.doctordetails'),
        ),
    ]
