# Generated by Django 4.2.16 on 2024-12-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H2H_admin', '0029_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=0),
        ),
    ]
