# Generated by Django 4.2.17 on 2024-12-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H2H_admin', '0035_remove_customerwallethistory_wallet_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerwallethistory',
            name='transaction_type_choices',
            field=models.CharField(choices=[('customer added amount', 'Customer added amount'), ('refund amount', 'Refund amount'), ('deducted amount', 'Deducted amount')], default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerwallethistory',
            name='transaction_type',
            field=models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=20),
        ),
    ]
