# Generated by Django 4.2.17 on 2024-12-12 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('H2H_admin', '0037_doctorbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorbooking',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinic_bookings', to='H2H_admin.doctorclinics'),
        ),
    ]
