# Generated by Django 4.2.17 on 2024-12-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H2H_admin', '0039_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='FcmNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('customer_title', models.CharField(max_length=100)),
                ('customer_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FCM Notification',
                'verbose_name_plural': 'FCM Notifications',
                'db_table': 'fcm_notifications',
            },
        ),
    ]
