# Generated by Django 4.2.17 on 2024-12-14 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_customer_created_at_and_more'),
        ('H2H_admin', '0040_fcmnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=150)),
                ('patient_dob', models.DateField()),
                ('patient_gender', models.CharField(max_length=10)),
                ('address_id', models.IntegerField()),
                ('promo_id', models.IntegerField()),
                ('discount', models.FloatField()),
                ('tax', models.FloatField()),
                ('sub_total', models.FloatField()),
                ('total', models.FloatField()),
                ('special_instruction', models.CharField(blank=True, max_length=250, null=True)),
                ('payment_mode', models.IntegerField()),
                ('booking_type', models.IntegerField(choices=[(1, 'Collect From Home'), (2, 'Lab Visit')], default=1)),
                ('items', models.TextField()),
                ('status', models.IntegerField(choices=[(1, 'Order Placed'), (2, 'Confirmed'), (3, 'Collective Person Assigned'), (4, 'On Progress'), (5, 'Report Ready To Dispatch'), (6, 'Completed')], default=1)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('appointment_time', models.TimeField(blank=True, null=True)),
                ('report', models.FileField(blank=True, null=True, upload_to='lab/reports/')),
                ('appointment_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='accounts.customer')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='accounts.laboratory')),
                ('lab_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='H2H_admin.labstaff', verbose_name='Collective Person')),
            ],
            options={
                'verbose_name': 'Lab Order',
                'verbose_name_plural': 'Lab Orders',
                'db_table': 'lab_orders',
            },
        ),
        migrations.CreateModel(
            name='LabOrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField()),
                ('item_name', models.CharField(max_length=150)),
                ('price', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_order_items', to='H2H_admin.laborders')),
            ],
            options={
                'verbose_name': 'Lab Order Item',
                'verbose_name_plural': 'Lab Order Items',
                'db_table': 'lab_order_items',
            },
        ),
    ]
