# Generated by Django 4.2.17 on 2024-12-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H2H_admin', '0041_laborders_laborderitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorbooking',
            name='status',
            field=models.CharField(choices=[('confirm', 'Confirm'), ('complete', 'Complete'), ('cancelled', 'Cancelled'), ('pending', 'Pending')], default='pending', max_length=255),
        ),
    ]
