# Generated by Django 4.2.16 on 2024-11-19 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_hospital_city'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hospitalimage',
            table='hospital_images',
        ),
    ]
