# Generated by Django 4.2.16 on 2024-11-20 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('H2H_admin', '0009_symptom'),
        ('accounts', '0004_alter_hospitalimage_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordetails',
            name='specialist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='H2H_admin.specialistcategory'),
        ),
    ]
