# Generated by Django 4.2.16 on 2024-11-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_doctordetails_specialist'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordetails',
            name='join_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
