# Generated by Django 4.2.16 on 2024-11-28 07:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_doctordetails_join_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='doctordetails',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='doctordetails',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='laboratory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='laboratory',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
