# Generated by Django 4.2.14 on 2024-08-24 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_alter_insurance_insurance_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospital_insurances', to='hospital.hospital')),
                ('insurance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurance_hospitals', to='hospital.insurance')),
            ],
            options={
                'db_table': 'hospital_insurance',
                'unique_together': {('hospital', 'insurance')},
            },
        ),
    ]
