# Generated by Django 4.2.14 on 2024-08-26 11:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
        ('hospital', '0005_hospitalinsurance'),
    ]

    operations = [
        migrations.CreateModel(
            name='BedBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1)),
                ('ward_type', models.CharField(max_length=255)),
                ('bed_type', models.CharField(max_length=255)),
                ('booking_type', models.CharField(max_length=255)),
                ('patient_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('contact_number', models.CharField(max_length=255)),
                ('emergency_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('blood_group', models.CharField(max_length=255)),
                ('medical_history', models.TextField(blank=True, null=True)),
                ('booking_reason', models.CharField(max_length=255)),
                ('insurance_info', models.TextField(blank=True, null=True)),
                ('admission_date', models.DateField()),
                ('discharge_date', models.DateField(blank=True, null=True)),
                ('booking_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_slot', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor_assigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bed_bookings', to='doctor.doctordetails')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bed_bookings', to='hospital.hospital')),
            ],
            options={
                'db_table': 'bed_bookings',
            },
        ),
    ]
