# Generated by Django 4.2.14 on 2024-08-31 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_bedbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedbooking',
            name='customer',
            field=models.IntegerField(choices=[('pending', 'Pending'), ('reject', 'Reject'), ('accepted', 'Accepted')], default=1),
        ),
        migrations.AlterField(
            model_name='bedbooking',
            name='status',
            field=models.IntegerField(choices=[('pending', 'Pending'), ('reject', 'Reject'), ('accepted', 'Accepted')], default=1),
        ),
    ]
