# Generated by Django 4.2.14 on 2024-08-31 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_alter_bedbooking_customer_alter_bedbooking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedbooking',
            name='customer',
            field=models.IntegerField(default=1),
        ),
    ]
