# Generated by Django 4.2.14 on 2024-08-31 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_alter_bedbooking_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedbooking',
            name='status',
            field=models.IntegerField(choices=[('pending', 'Pending'), ('reject', 'Reject'), ('accepted', 'Accepted')], default='pending'),
        ),
    ]
