# Generated by Django 4.2.14 on 2024-09-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0015_customer_groups_customer_is_superuser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='profile_picture',
            field=models.ImageField(default='hospital/customer_profile/avatar.png', upload_to='hospital/customer_profile/'),
        ),
    ]
