# Generated by Django 4.2.14 on 2024-09-13 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_alter_hospital_latitude_alter_hospital_longitude_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='admin',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
