# Generated by Django 4.2.14 on 2024-09-21 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorSpecialistCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
                ('category_image', models.ImageField(blank=True, null=True, upload_to='doctors/doctor_specialist_category_images/')),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom_name', models.CharField(max_length=255)),
                ('symptom_image', models.ImageField(blank=True, null=True, upload_to='doctors/symptom_images/')),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('specialist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='symptoms', to='doctor.doctorspecialistcategory')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dr_name', models.CharField(max_length=255)),
                ('dr_unique_code', models.CharField(max_length=50, unique=True)),
                ('qualification', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('dr_username', models.CharField(max_length=100, unique=True)),
                ('experience', models.PositiveIntegerField(default=1)),
                ('sub_specialist', models.CharField(blank=True, max_length=100, null=True)),
                ('additional_qualification', models.TextField(blank=True, null=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('overall_ratings', models.FloatField(default=0)),
                ('document_update_status', models.IntegerField(default=0)),
                ('document_approve_status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], default='P', max_length=1)),
                ('profile_status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], default='P', max_length=1)),
                ('online_status', models.CharField(choices=[('O', 'Online'), ('F', 'Offline')], default='F', max_length=1)),
                ('medical_license', models.CharField(max_length=100, unique=True)),
                ('institution', models.CharField(max_length=255)),
                ('graduation_year', models.PositiveIntegerField()),
                ('dob', models.DateField()),
                ('join_date', models.DateField(auto_now_add=True)),
                ('c_id', models.IntegerField(default=0)),
                ('c_stat', models.IntegerField(default=0)),
                ('wallet', models.FloatField(default=0)),
                ('earnings', models.FloatField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('fcm_token', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=1)),
                ('is_recommended', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='doctors/doctor_profiles/')),
                ('resume', models.ImageField(blank=True, null=True, upload_to='doctors/doctor_documents/')),
                ('medical_license_doc', models.ImageField(blank=True, null=True, upload_to='doctors/doctor_documents/')),
                ('certification', models.ImageField(blank=True, null=True, upload_to='doctors/doctor_documents/')),
                ('other', models.ImageField(blank=True, null=True, upload_to='doctors/doctor_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='hospital.hospital')),
                ('specialist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='doctor.doctorspecialistcategory')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorClinics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('consultation_minutes', models.CharField(default='0', max_length=10)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('status', models.IntegerField(default=0)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.cliniccategory')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinics', to='doctor.doctordetails')),
            ],
        ),
    ]
