# Generated by Django 4.2.16 on 2024-09-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_doctorbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorbooking',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
    ]
