# Generated by Django 4.2.16 on 2024-09-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_alter_doctorbooking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorbooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accept'), ('rejected', 'Reject'), ('cancelled', 'Cancelled'), ('successful', 'Successful')], default='pending', max_length=10),
        ),
    ]
